name: Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Archive packages directory
        run: |
          zip -r template-library.zip packages manifests docs/changelog.md

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: template-library.zip
